name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmPlKfohb6/oZjYLuDuJHpr+UkeF4TOJdplpNP+if7ugujTYzj+XSEER1O3WFXhtaZiPgCGQ8tvFYvtCQTyVQP2/9ajncGhur9sbewA3Pt8lqG2X7Vy0DEZmsSXexLMspJdfSmPAcTeAU/dXqFVmDK3NX3dc5fffEADcdG+ImIYndPcAmwpfigrlmZYV47da8WNBqAKVcjsG8Ulm53iGrIwu4lyJJJ3v9eA5n5YFvMfRrO5f267a0VHFKFUviMJLsdHGE2I7jEQMqh07+hgNQaA234THpruFbtHslu1VZwh+wBUNRlS0Sx5u4x38KbRZy4jvgW7iUPsGLNtP0bhv4d7TatCmk1mvLAa3nK07aSQ2SeGZP2ob6iXOfGnIW9lsbNB5dTKYnQeJQ9kP/7FPPghyo5bmfKqWk8+2l6xDfFbH3UrpQwG1tuS5z53gQkW02gqZJKEZcsRZy8Ior+a9Tmaz9wb+xONdHIYEWX1jucpf00FA9SKVumIttpVXfAvq+Qwc1LmGW6fFwda9o6AScudWLyFpyUmlJdeYXtU72fl8nO4esjeKTqN+o20akkaeRNG/7okxY4a9622YvkW3+Ox3dOBRgbfhiXmB2hcLSLNe2c0Ijgu1Mja3BLNFyIRfkvzrOnU3RkHGWkNYGi13f3UhRMSD+MC8Agply0SNoGoQ== Praktikan45
            echo "Cek folder project";
            [ ! -d "${HOME}/senpro/544527/modul02/senpro-github-action/" ] &&
            {
              echo "Repository belum di-clone. Cloning...";
              mkdir -p ~/senpro/544527/modul02;
              cd ~/senpro/544527/modul02;
              git clone https://github.com/MonicaTasya/senpro-github-action.git;
              cd ~/senpro/544527/modul02/senpro-github-action;
              echo "Install Package dan Build Project";
              npm install;
              npm run build;
            } ||
            {
              echo "Repository sudah ada. Building...";
              cd ~/senpro/544527/modul02/senpro-github-action;
              git restore .;
              git pull origin main;
              echo "Install Package dan Build Project";
              npm install;
              npm run build;
            }